### ISSUE TITLE
FE - Implement Profile Management API

### ISSUE THREAD

**Issue by sanjaysah101** [ansopedia/users#19]
**Description:**

The current Ansopedia user service lacks a dedicated API for detailed profile management. This limits users' control over their information and visibility.

**Proposed Solution:**

We propose a comprehensive profile management API within the user service, enabling users to:

- **Create and Update Profiles:** Users can manage their profiles with the following details:
  - Personal Information (name, email, phone number, etc.)
  - Social Media Links (optional)
  - Address (optional)
  - **isVerified** (boolean): Flag indicating verified user information (e.g., email/phone verification).
  - **isPublic** (boolean): Flag controlling profile visibility to other users.
  - **Educational Details:**
    - List of Schools Attended (name, location, degree, graduation year - optional)
    - List of Colleges/Universities Attended (name, location, degree, graduation year - optional)

**Current Scenario:**

Currently, we have a `GET ...api/v1/users/username` API endpoint to fetch user details. We propose extending this functionality by:

- Creating a dedicated profile collection in MongoDB to store the above-mentioned fields.
- Implementing API logic to handle user requests based on different scenarios, including:

  - **Public vs. Private Profiles:**
    - Default `isPublic` status is `true` (profile publicly visible).
    - Users can control visibility with the `isPublic` flag.
  - **Account Verification:**
    - Default `isVerified` status is `false`.
    - Users may need to verify their email before updating profiles (implementation detail to be discussed).
    - Unverified accounts face temporary restrictions (specific actions to be decided).

**Implementation Considerations:**

- Implement conditions in `profile.service.ts` for different API requests (GET, POST):
  - **GET:**
    - Handle non-existent user with a 404 error and appropriate message.
    - If the requested profile is private (`isPublic` is `false`), return a message indicating the account's privacy.
    - For unverified accounts (`isVerified` is `false`):
      - If the requesting user and profile owner don't match, return a message about `temporary account blocking` and login to see steps to reactivate.
      - If the requesting user matches the profile owner, inform them about the need for email verification before profile updates.
    - Finally, return the user details upon successful retrieval.
  - **POST:** (Details to be discussed further)
    - Consider requiring email verification (`isVerified` to be `true`) before profile updates.
    - Define appropriate error handling for failed updates.

**Benefits:**

- Enhanced user experience with control over profile data and visibility.
- Centralized profile management within the user service for better data handling.
- Improved user profiles with richer information for Ansopedia functionalities.

**Comment by lord-mallik** [comment]
Here are the key consideration points for implementing the profile management API:

## Implementation Considerations

1. **Privacy and Access Control:**
- Implement checks for isPublic flag to control profile visibility.
- Ensure only verified users (when isVerified is true) can perform certain actions or access specific profile details.
- Restrict access to unverified accounts by showing a relevant message or prompting for verification.

2. **Error Handling:**
- Return a 404 error for non-existent user profiles.
- Provide clear error messages for actions that are restricted due to privacy settings or verification status.
- Define standardized error codes and messages for failed updates or retrieval attempts.

3. **Security:**
- Implement authentication and authorization to ensure only authorized users can access or modify profiles.
- Use HTTPS to protect data during transmission.
- Perform regular security audits and updates.

4. **Data Validation and Sanitization:**
- Validate all input data (e.g., email format, phone number, etc.) to prevent invalid data entry.
- Sanitize inputs to prevent SQL injection, XSS, or other malicious attacks.

5. **Scalability:**
- Design the API and database schema to efficiently handle a large number of users and profiles.
- Optimize queries and consider indexing frequently accessed fields for performance.

6. **Performance Optimization:**
- Minimize response times by optimizing database queries and caching frequently accessed data.
- Ensure the API can handle concurrent requests without significant performance degradation.

7. **User Experience:**
- Clearly communicate default settings (e.g., isPublic is true) and provide easy options for users to change them.
- Notify users of changes in their profile status (e.g., after verification) through emails or in-app notifications.

8. **Data Integrity and Consistency:**
- Ensure consistency between user data across different services within Ansopedia.
- Implement data integrity checks during profile creation and updates.

These considerations will help ensure that the profile management API is robust, secure, and provides a seamless experience for users.

**Comment by sanjaysah101** [comment]
To be covered in #60 #61 #62 #63 #64
